import { declare } from '../../declare';
import { Interact } from '../Interact';

describe('Interact', () => {
    const api = declare({
        test: {
            worker: (num1: number) => num1 + 10,
        },
    });

    describe('with', () => {
        it("should throw if the function passed in wasn't generated by ThreadzAPI", () => {
            expect(() => Interact.with(async () => 'hi')).toThrow();
        });

        it('should return a new Interact instance', () => {
            expect(Interact.with(api.workers.test)).toBeInstanceOf(Interact);
        });
    });
});
